### PR TITLE
Use direct path in testpoolswap when available

### LINKED ISSUE #1114: `testpoolswap` RPC should check for a direct swap first when `auto` is specified.
#### What happened:
1. add a CAT-DFI pool.
2. call `testpoolswap` from CAT -> DFI with `path = auto`, `verbose = true`
3. response have as follows. note `pools` field.
`{ path: 'auto', pools: [ '2', '2', '2' ], amount: '48.48437068@0' }`

The above should be a direct swap since `CAT-DFI`  pool is present.
RCA
even in `compositeswap` check for a direct swap is done first and then goes to the `CalculateSwaps()` and `compositeswap()`
ref -> https://github.com/DeFiCh/ain/blob/c0a25f727f32c1b2c32a5120059276ec97e38bd2/src/masternodes/rpc_poolpair.cpp#L919

but in the scenario mentioned above, it will call `CalculateSwaps()` straight. ref -> https://github.com/DeFiCh/ain/blob/c0a25f727f32c1b2c32a5120059276ec97e38bd2/src/masternodes/rpc_poolpair.cpp#L1091

it could be that the `CalculateSwaps()` is unable to handle this scenario well.
But simply adding a check for a direct swap first should solve the issue(same as the `compositeswap` flow. ).
https://github.com/DeFiCh/ain/blob/c0a25f727f32c1b2c32a5120059276ec97e38bd2/src/masternodes/rpc_poolpair.cpp#L1091

### PR DESCRIPTION
**Pull request by Jouzo**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:

Uses direct path in testpoolswap when available

#### Which issue(s) does this PR fixes?:

Fixes #1114

### CODE REVIEW

**Review by Bushstar — DISMISSED** [review]

**Comment by eli-lim** [comment]
Just curious, which of the following are we looking to achieve for `testpoolswap`?
- Always use direct path if available
- Use _best_ path (implying some composite path may yield an amount greater than direct - assuming that's possible)

**Comment by Jouzo** [comment]
> Just curious, which of the following are we looking to achieve for `testpoolswap`?
> 
>     1. Always use direct path if available
> 
>     2. Use _best_ path (implying some composite path may yield an amount greater than direct - assuming that's possible)
> 
> 
> Asking because if (2) is preferred, the logic could instead be in `CPoolSwap::CalculatePoolPaths`.

Good question. Here I addressed the issue by going for the first option but that might not always be the best scenario. 
Another option would be to add "composite" to the accepted path values which would always test for `compositeswap`.
Then we would have:
-  `direct`: Always test for a `poolswap`
- `composite`: Always test for a `compositeswap`
- `auto`: Use a direct swap via `poolswap` if available (as currently in this PR) or go through `compositeswap`
- [poolpairs_ids]: Try through a custom path

With this additional path, a user could try for `direct` vs `composite` and choose the best of two paths (scenario 2).

**Review by surangap — APPROVED** [review]

**Comment by surangap** [comment]
> 




> > Just curious, which of the following are we looking to achieve for `testpoolswap`?
> > ```
> > 1. Always use direct path if available
> > 
> > 2. Use _best_ path (implying some composite path may yield an amount greater than direct - assuming that's possible)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Asking because if (2) is preferred, the logic could instead be in `CPoolSwap::CalculatePoolPaths`.
> 
> Good question. Here I addressed the issue by going for the first option but that might not always be the best scenario. Another option would be to add "composite" to the accepted path values which would always test for `compositeswap`. Then we would have:
> 
> * `direct`: Always test for a `poolswap`
> * `composite`: Always test for a `compositeswap`
> * `auto`: Use a direct swap via `poolswap` if available (as currently in this PR) or go through `compositeswap`
> * [poolpairs_ids]: Try through a custom path
> 
> With this additional path, a user could try for `direct` vs `composite` and choose the best of two paths (scenario 2).

saw this later. I guess it could be possible that a composite swap yields more than the direct swap 🤔
I think the main problem is that `CalculateSwaps ` is not able to handle the scenario where only the direct pool is available and no other path. need to write a unit test and confirm it.

**Comment by eli-lim** [comment]
> > 
> 
> > > Just curious, which of the following are we looking to achieve for `testpoolswap`?
> > > ```
> > > 1. Always use direct path if available
> > > 
> > > 2. Use _best_ path (implying some composite path may yield an amount greater than direct - assuming that's possible)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Asking because if (2) is preferred, the logic could instead be in `CPoolSwap::CalculatePoolPaths`.
> > 
> > 
> > Good question. Here I addressed the issue by going for the first option but that might not always be the best scenario. Another option would be to add "composite" to the accepted path values which would always test for `compositeswap`. Then we would have:
> > 
> > * `direct`: Always test for a `poolswap`
> > * `composite`: Always test for a `compositeswap`
> > * `auto`: Use a direct swap via `poolswap` if available (as currently in this PR) or go through `compositeswap`
> > * [poolpairs_ids]: Try through a custom path
> > 
> > With this additional path, a user could try for `direct` vs `composite` and choose the best of two paths (scenario 2).

`composite` here would mean "use the best possible composite swap path"? I would think that's a pretty niche use-case 😮.
Regarding the user trying both options - we probably want to avoid having to make 2 RPCs as it would be a performance / UX impediment for wallet users.

> saw this later. I guess it could be possible that a composite swap yields more than the direct swap 🤔 I think the main problem is that `CalculateSwaps ` is not able to handle the scenario where only the direct pool is available and no other path. need to write a unit test and confirm it.

Agree. Deeper - `CalculatePoolPaths` doesn't ever consider a direct path. So we could just have the logic there instead.
Then `auto` would return the "best" among the direct and possible composite paths, since the direct path is also included in the `CalculateSwaps` evaluation.

**Review by prasannavl — APPROVED** [review]

**Pull request merged**
