### PR TITLE
Fix logic balances less than other ones

### PR DESCRIPTION
**Pull request by bvbfan**
Could you guys can verify it's finally the right fix. When we compare balances when some of the right balances is higher than left one, it's mean left is less than right one.

### CODE REVIEW

**Comment by ShengguangXiao** [comment]
Can add some unittest cases to verify the comparison results?

**Comment by bvbfan** [comment]
`feature_any_accounts_to_accounts` use it.

**Comment by ShengguangXiao** [comment]
> `feature_any_accounts_to_accounts` use it.

It will be better if have some C++ unittest directly do the comparison.

**Comment by bvbfan** [comment]
I've going to remove `GetAllTokensAmount` sum all amounts despite token is quite useless, about me. Also it can overflow int, also i don't see how it works correct when you have [`1@1`, `8@2`] and [`3@1`,  `5@2`] so sorted depend of sum1 and sum2.

**Pull request merged**
