### PR TITLE
Better handling of account history

### PR DESCRIPTION
**Pull request by bvbfan**
This a WIP, i have plan to store rewards by pool id as well, should we have it for account history as well? Now we have owner <-> token <-> amount, but if it's not a pool account we can use token id instead?

### CODE REVIEW

**Comment by monstrobishi** [comment]
much nicer can you confirm if this has an impact on performance

**Comment by bvbfan** [comment]
It's a bit faster, really small, what's save is serialize/deserialize to stream. I plan to make another class to handle rewards and to store rewards by pool id (in validation.cpp where rewards are redistributed)

**Review by ShengguangXiao — APPROVED** [review]

**Comment by monstrobishi** [comment]
@bvbfan is this still a work in progress? you can change the title when you feel it's ready to merge in

**Comment by bvbfan** [comment]
It's no more a WIP, rewards are two types, `Commission` and `PoolReward` they are stored separate from account history.

**Comment by bvbfan** [comment]
`listaccounthistory` rpc call remains unchanged for account history, it has `txid` and `txn` the difference is there is no empty `txid` anymore, it means when it has `txid` it's account history, `Rewards` type is split to `Commission` and `PoolReward`, also rewards have `poolID`.
Account:
`owner`
`blockHeight`
`type` (`Rewards` is not valid type anymore)
`txn`
`txid`
`amounts`
Reward:
`owner`
`blockHeight`
`type` (`Commission` or `PoolReward`)
`poolID`
`amounts`

**Comment by monstrobishi** [comment]
this could break the app if the Rewards type does not exist anymore, can we name "PoolReward" back to "Rewards" so that the type still exists, and split commission out

**Comment by bvbfan** [comment]
Added https://github.com/cakedefi/defichain-private/issues/63

**Comment by monstrobishi** [comment]
@bvbfan after merging the other PR (for including UTXO) this has quite a few conflicts

**Comment by bvbfan** [comment]
Rebased.

**Comment by bvbfan** [comment]
All unit tests pass locally, changes not affect wallet at all.

**Review by monstrobishi — APPROVED** [review]

**Comment by bvbfan** [comment]
@Bushstar can you test new approach?

**Review by Bushstar — APPROVED** [review]

**Pull request merged**
