### PR TITLE
[Needs tests] Fix/limit blocktime range

### PR DESCRIPTION
**Pull request by bvbfan**
/kind fix

#### What this PR does / why we need it:

Limit the range of block time to -+ 60 sec to local node time

### CODE REVIEW

**Comment by muirglacier** [comment]
Do not merge this pull request, it will break the entire blockchain.

In CheckContextualBlockHeader() you just check whether the blocktime is NOW()-60 or lower, and when it is then you reject the block. What if a node is syncing from scratch - i.e. synching old blocks to catch up to the current height? All those blocks would be falsely INVALID.

**Comment by bvbfan** [comment]
Functional tests does not follow new block time range.

**Comment by uzyn** [comment]
@hidiego Please update the tests.

**Comment by uzyn** [comment]
Thanks @bvbfan Closing this for https://github.com/DeFiCh/ain/issues/575

**Pull request closed without merging**
