### PR TITLE
Split pool reward records

### PR DESCRIPTION
**Pull request by bvbfan**
/kind fix

#### What this PR does / why we need it:
Pool and custom rewards to be distinct history items

Fixes https://github.com/cakedefi/defichain-private/issues/393

### CODE REVIEW

**Comment by monstrobishi** [comment]
Will this return 2 types of account history for custom rewards and regular rewards? Ideally they should both be "Rewards" from the user's perspective

**Comment by bvbfan** [comment]
Yes it'll be distinct, so it should be 2 records but as same `Rewards` type?

**Comment by monstrobishi** [comment]
Yes the format in listaccounthistory should show `Reward` in both cases, the user doesn't care how the reward was set on the backend

**Comment by bvbfan** [comment]
Split records not types.

**Review by monstrobishi — APPROVED** [review]

**Pull request merged**
