### PR TITLE
Refactor test framework into node and fixture utility scripts

### PR DESCRIPTION
**Pull request by sieniven**
## Summary

Refactor test framework to remove node and fixture utility functions into separate utility scripts.

## Implications

- Storage
  - [ ] Database reindex required
  - [ ] Database reindex optional
  - [ ] Database reindex not required
  - [x] None

- Consensus
  - [ ] Network upgrade required
  - [ ] Includes backward compatible changes
  - [ ] Includes consensus workarounds
  - [ ] Includes consensus refactors
  - [x] None

### CODE REVIEW

**Comment by prasannavl** [comment]
Rebasing this to master.

**Comment by prasannavl** [comment]
Also, how about instead of using free functions and importing them which doesn't really provide much context when it's being used in a large code base, use a class called `Fixture` that's imported. 

`Fixture.setup_token_default`
`Fixture.setup_token_some_exotic_scenario`
`Fixture.something_other_setup`

Etc

Two key advantages: 
- Throughout it's use, we knows it's operating on a fixture setup. 
- Just one or two classes this way to import without having to worry about what to import and what not to import

**Review by shohamc1 — COMMENTED** [review]
LGTM, needs new lines at the end of the files to fix linter errors though.

**Review by shohamc1 — DISMISSED** [review]

**Comment by sieniven** [comment]
Closed as this PR is continued in #1920.

**Pull request closed without merging**
