### PR TITLE
Migrate Travis to Github workflows

### PR DESCRIPTION
**Pull request by monstrobishi**
#### What kind of PR is this?:

/kind chore

#### What this PR does / why we need it:

Migrate Travis to Github workflows

#### Which issue(s) does this PR fixes?:

Fixes #

### CODE REVIEW

**Comment by monstrobishi** [comment]
Wait forgot to remove Travis, let me do that

**Comment by monstrobishi** [comment]
Not removing Travis yet, merge this in first (so Travis tests pass on this PR), then we remove Travis

**Review by fuxingloh — APPROVED** [review]

**Comment by monstrobishi** [comment]
The branch unit test passed but the PR one failed, running it again incase it's an intermittent one

**Comment by monstrobishi** [comment]
ok it passed that time 🎉

**Pull request merged**
