### PR TITLE
Fix list rpc consistency

### PR DESCRIPTION
**Pull request by hidiego**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:
Add additional parameter `jsonformat ("list" | "object")` to list* RPCs:
- `jsonformat = "list" -> [ {obj}, {obj} ]` 
- `jsonformat = "object" -> { key: {obj}, key: {obj} }`

### CODE REVIEW

**Comment by Jouzo** [comment]
What about getting isList value from flag instead of parameter ?

**Comment by bvbfan** [comment]
@Jouzo you can write more about flag vs parameter, pro / cons?

**Comment by Jouzo** [comment]
Pros and cons of using `jsonformat` as parameter :

Pros :

- More granular
- Better backward compatibility

Cons:

- Inconsistencies between different list calls. Ex :
    - `listaccounthistory`/`listburnhistory`/`listreceivedbyaddress`/`listunspent` - `jsonformat` is a key in `options` object
    - All the others take `jsonformat` as string parameter

- A call such as `listaccounts` gets even more arcane with `defi-cli listaccounts {} false false true object`

- Boilerplate added to each list* RPCs

- Potential missing parameter in CRPCCommand. Harder to keep track.

---

It's to be noted than only `listmasternodes`, `listpoolpairs`, `listpoolshares` and `listtokens` have a default value of `object`.

**Comment by Jouzo** [comment]
I wondered if the `object` value will be used but for backward compatibility.

- Object keys does not make a lot of sense in certain case such as :

```
defi-cli listaccounts {} false false true object
{
  "0": {
    "key": "001420d230f5ae43bc1a66f1c96f196f95b3be2a8466@2",
    "owner": "bcrt1qyrfrpadwgw7p5eh3e9h3jmu4kwlz4prx73cqny",
    "amount": "1000.00000000@GOOG"
  },
  "1": {
    "key": "001420d230f5ae43bc1a66f1c96f196f95b3be2a8466@4",
    "owner": "bcrt1qyrfrpadwgw7p5eh3e9h3jmu4kwlz4prx73cqny",
    "amount": "1000.00000000@TSLA"
  }
}
```

or can be confusing (which id is the correct token id in that case ?) :
```
defi-cli listloantokens object 
{
  "0": {
    "token": {
      "2": {
        "symbol": "GOOG",
        "symbolKey": "GOOG",
        "name": "GOOG token",
        "decimal": 8,
        "limit": 0,
        "mintable": true,
        "tradeable": true,
        "isDAT": true,
        "isLPS": false,
        "finalized": false,
        "isLoanToken": true,
        "minted": 1000.00000000,
        "creationTx": "017c531e95ff1af18d7e43dd48bd55940a992429337b0a0d4e165cc24027454c",
        "creationHeight": 4631,
        "destructionTx": "0000000000000000000000000000000000000000000000000000000000000000",
        "destructionHeight": -1,
        "collateralAddress": "bcrt1qyrfrpadwgw7p5eh3e9h3jmu4kwlz4prx73cqny"
      }
    },
    "fixedIntervalPriceId": "GOOG/USD",
    "interest": 1.00000000
  }
```

**Comment by bvbfan** [comment]
I think `listloantokens object` is a bug, the key should be token id (2), `fixedIntervalPriceId` and `interest` should be under that key as well. I suppose @hidiego made lesser code universal approach. @Jouzo  by flag you mean a global one, let's say `rpc_json object | list`?

**Comment by Jouzo** [comment]
The four list RPC that send their result as object are :
- `listmasternodes`
- `listpoolpairs`
- `listpoolshares`
- `listtokens`

The other list RPC from upstream are sending their result as array. 

---

I wondered if this inconsistency is a voluntary design decision from that time.

Here are a few examples from these RPC calls :
```
defi-cli listpoolshares '{"limit":2}'
{
  "4@df1qqrc60esmrmjdd2n8qqcs2j8c86ceqnyyrytm5r": {
    "poolID": "4",
    "owner": "df1qqrc60esmrmjdd2n8qqcs2j8c86ceqnyyrytm5r",
    "%": 0,
    "amount": 323.51823644,
    "totalLiquidity": 315506.04379292
  },
  "4@df1qq82gkwps83xzlwzs234elpwrzquz22we0m5mxn": {
    "poolID": "4",
    "owner": "df1qq82gkwps83xzlwzs234elpwrzquz22we0m5mxn",
    "%": 0,
    "amount": 127.54047384,
    "totalLiquidity": 315506.04379292
  }
}
```

```
defi-cli listtokens '{"limit":2}'
{
  "0": {
    "symbol": "DFI",
    "symbolKey": "DFI",
    "name": "Default Defi token",
    "decimal": 8,
    "limit": 0,
    "mintable": false,
    "tradeable": true,
    "isDAT": true,
    "isLPS": false,
    "finalized": true,
    "minted": 0.00000000,
    "creationTx": "0000000000000000000000000000000000000000000000000000000000000000",
    "creationHeight": 0,
    "destructionTx": "0000000000000000000000000000000000000000000000000000000000000000",
    "destructionHeight": -1,
    "collateralAddress": ""
  },
  "1": {
    "symbol": "ETH",
    "symbolKey": "ETH",
    "name": "Ether",
    "decimal": 8,
    "limit": 0,
    "mintable": true,
    "tradeable": true,
    "isDAT": true,
    "isLPS": false,
    "finalized": false,
    "minted": 14960.00000000,
    "creationTx": "2fb0ce8208392e488964e78a93efe0713c36b5b98afe600da48805498e97b8e6",
    "creationHeight": 466549,
    "destructionTx": "0000000000000000000000000000000000000000000000000000000000000000",
    "destructionHeight": -1,
    "collateralAddress": "8RbpgySS2qkXQG2UosQCqADtS7zRAr8bx5"
  }
}
```

```
defi-cli listpoolpairs '{"limit":2}'
{
  "4": {
    "symbol": "ETH-DFI",
    "name": "Ether-Default Defi token",
    "status": true,
    "idTokenA": "1",
    "idTokenB": "0",
    "reserveA": 8471.22650550,
    "reserveB": 11758940.03459917,
    "commission": 0.00200000,
    "totalLiquidity": 315434.92785712,
    "reserveA/reserveB": 0.00072040,
    "reserveB/reserveA": 1388.10360305,
    "tradeEnabled": true,
    "ownerAddress": "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb",
    "blockCommissionA": 0.00000000,
    "blockCommissionB": 0.00000000,
    "rewardPct": 0.14549000,
    "creationTx": "9827894c083b77938d13884f0404539daa054a818e0c5019afa1eeff0437a51b",
    "creationHeight": 466822
  },
  "5": {
    "symbol": "BTC-DFI",
    "name": "Bitcoin-Default Defi token",
    "status": true,
    "idTokenA": "2",
    "idTokenB": "0",
    "reserveA": 2532.30206610,
    "reserveB": 49622448.16048241,
    "commission": 0.00200000,
    "totalLiquidity": 354449.75375240,
    "reserveA/reserveB": 0.00005103,
    "reserveB/reserveA": 19595.78552052,
    "tradeEnabled": true,
    "ownerAddress": "8UAhRuUFCyFUHEPD7qvtj8Zy2HxF5HH5nb",
    "blockCommissionA": 0.00000000,
    "blockCommissionB": 0.00000000,
    "rewardPct": 0.77594500,
    "creationTx": "f3c99e199d0157b2b6254cf3a51bb1171569ad5c4beb797e957d245aec194d38",
    "creationHeight": 466826
  }
}
```

```
defi-cli listmasternodes '{"limit":2}'
{
  "095d2bfb5d05ba73fa96502df85aca818ee79810b9ababa71a9dc97e2c360100": {
    "ownerAuthAddress": "8N76H2YQcayUZECp25DMNY1nQw6HUouMSR",
    "operatorAuthAddress": "8aoZkCXa5B423vzMq8LMiBF7m7NGGj6KCT",
    "creationHeight": 1120444,
    "resignHeight": -1,
    "resignTx": "0000000000000000000000000000000000000000000000000000000000000000",
    "banTx": "0000000000000000000000000000000000000000000000000000000000000000",
    "state": "ENABLED",
    "mintedBlocks": 59,
    "ownerIsMine": false,
    "operatorIsMine": false,
    "localMasternode": false,
    "targetMultipliers": [
      57,
      57,
      44,
      46
    ],
    "timelock": "10 years"
  },
  "e54d0814d406317dfaa38f365471ff59fb7f7725769c0aecf3d0830a59de0100": {
    "ownerAuthAddress": "8XctLWjNsRJByMrYCgNxqyw9F1JhGYoDNb",
    "operatorAuthAddress": "8bvAc8UAEpA4dmLSWHsmPbxqZ5w8qxjDxH",
    "creationHeight": 1091445,
    "resignHeight": -1,
    "resignTx": "0000000000000000000000000000000000000000000000000000000000000000",
    "banTx": "0000000000000000000000000000000000000000000000000000000000000000",
    "state": "ENABLED",
    "mintedBlocks": 56,
    "ownerIsMine": false,
    "operatorIsMine": false,
    "localMasternode": false,
    "targetMultipliers": [
      57,
      57,
      43,
      57
    ],
    "timelock": "10 years"
  }
}
```

What is the key in each of these calls ? Hard to say as a new user and would be clearer in an array as key/value.

In that case, why do we even need the possibility to send current list array RPC as object with `jsonformat=object` ?
If we get rid of this need, we can do with a much lighter PR that just adds a flag to the config that would fix these 4 RPCs and we don't have to add extra complexity and boilerplate to every list* RPC.

**Comment by prasannavl** [comment]
Leaving an update summary for reference: 

This is something that's needed to be addressed clearly and everyone agrees. However, after back and forths on this, we've been unable to achieve team consensus on a happy path on how to achieve this short of a new cleaner RPC, for quite some time.

So, shelving at this to a stage to just do pagination, so the functionality to query large sets is still there, and then focus future efforts on new brand new RPC. The inconsistency can live on in these 4 RPCs for as long as v1 RPC is alive.

**Pull request closed without merging**
