### PR TITLE
Ensure auto auth not overlap regular tx inputs or vice versa

### LINKED ISSUE #346: Lock unspents when performing custom transaction RPC calls
#### What would you like to be added:

Lock unspents when funding custom transaction RPC calls. See the following code sections:

https://github.com/DeFiCh/ain/blob/e85a9b5e62af04de8ed062bf93bf3bbb2961e99e/src/masternodes/mn_rpc.h#L67
https://github.com/DeFiCh/ain/blob/e85a9b5e62af04de8ed062bf93bf3bbb2961e99e/src/masternodes/rpc_poolpair.cpp#L346

and more...

This should simply require setting `lockUnspents` to `true` on all custom transactions that use the `fund` funcrtion.

Testing is required to ensure that this solves the issue, and does not cause further problems.

#### Why is this needed:

Locking unspents may help solve some mempool issues where a transaction conflicts in mempool over the UTXOs used to fund the transaction.

### PR DESCRIPTION
**Pull request by bvbfan**
/kind fix

#### What this PR does / why we need it:

It prevents conflicting inputs between auto auth and regular tx

Fixes #346

### CODE REVIEW

**Review by fuxingloh — DISMISSED** [review]

**Review by ShengguangXiao — DISMISSED** [review]

**Comment by uzyn** [comment]
@bvbfan thanks for the fix. What's the actual fix? Force pushes makes it hard to see what was changed.

**Review by uzyn — CHANGES_REQUESTED** [review]
@bvbfan please highlight the changed lines on how you resolve the deadlock so it can be reviewed.

**Comment by bvbfan** [comment]
Lock guard against `IsLockedCoin` and `LockCoin`. If still has a problem node should be build with `-DDEBUG_LOCKORDER` in configure CPPFLAGS

**Comment by uzyn** [comment]
@bvbfan Can you point to the line please?

**Comment by bvbfan** [comment]
https://github.com/DeFiCh/ain/pull/355/commits/884087c37af48ea306faa7306facb63c89381385#diff-ba67014e2d95f2d4dede7733866765778bf140c45e87e3f40a10bbeb923563d2R114
https://github.com/DeFiCh/ain/pull/355/commits/884087c37af48ea306faa7306facb63c89381385#diff-ba67014e2d95f2d4dede7733866765778bf140c45e87e3f40a10bbeb923563d2R137
https://github.com/DeFiCh/ain/pull/355/commits/884087c37af48ea306faa7306facb63c89381385#diff-ba67014e2d95f2d4dede7733866765778bf140c45e87e3f40a10bbeb923563d2R365
There is no many changes.

**Review by Bushstar — DISMISSED** [review]

**Review by monstrobishi — DISMISSED** [review]

**Review by fuxingloh — DISMISSED** [review]
ACK BUILD `defichain-HEAD-4d4cbda-x86_64-w64-mingw32` from https://github.com/DeFiCh/ain/actions/runs/801666694
Solved mempool conflict issue with AutoAuth. 

You should rebase your commits from master, and drop the merged commits. There are 8 files changes now.

**Review by uzyn — CHANGES_REQUESTED** [review]
Tried it: deadlock issues when `AddToWallet` even before any transactions are made.

**Review by uzyn — APPROVED** [review]
Works now after `-zapwallettxes=1`. Guess old transactions in mempool still messes it up on the coin locks.

**Review by monstrobishi — APPROVED** [review]

**Review by fuxingloh — APPROVED** [review]

**Pull request merged**
