### PR TITLE
Skip collateral factor check

### LINKED ISSUE #1509: skip collateral_factor check when `-jellyfish_regtest` args are present
#### What would you like to be added:

We need https://github.com/DeFiCh/ain/pull/1473 this merged and released.

#### Why is this needed:

While the idea of introducing a collateral factor check is valid and undoubtedly justified for obvious reasons, it presents difficulty to downstream applications that rely on the previous condition to be valid. Once we grandfathered a scenario such as this in, it's almost an impossible feat to change them.

On JellyfishSDK alone, over 500 unique tests were mocked within the construct of the previous condition. Changing those tests isn't a small feat, as manual calculations were done and estimated many months of effort were poured into that. We simply don't have the resources right now, as the team is working on MetaChain. If we were to add in DeFiScan and DeFiChain Wallet tests, that's at least a few thousand scenarios and >10k assertions that must be updated. 

Currently, those subsystems are using a "HEAD" image of #1473 for testing. Which isn't sustainable, we need #1473, or a version of it merged so that JellyfishSDK and its ecosystem can follow the latest release.

### PR DESCRIPTION
**Pull request by shohamc1**
#### What kind of PR is this?:

/kind feature

#### Which issue(s) does this PR fixes?:

Fixes #1509

#### Additional comments?:

Supersedes #1473

### CODE REVIEW

**Comment by fuxingloh** [comment]
Adding myself to the approval list, I will checkout this branch and test it.

**Comment by fuxingloh** [comment]
@shohamc1 do you mind taking a look at this test https://github.com/JellyfishSDK/jellyfish/actions/runs/3271588607/jobs/5381935157

I think a recent change to the master branch might have affected it. Is it an issue?

**Comment by shohamc1** [comment]
@fuxingloh they all seem to be related to changes in #1481. I believe the tests need to be updated.

**Comment by fuxingloh** [comment]
> @fuxingloh they all seem to be related to changes in #1481. I believe the tests need to be updated.

They're safe to update?

Given that it was a drastically different outcome for expected and received. Do you have better insights into this? Do you mind sharing?

```
Expected substring: "Price is higher than indicated"
Received message:   "RpcApiError: 'Cannot find usable pool pair.', code: -32600, method: testpoolswap"
```

```
Expected substring: "Lack of liquidity"
Received message:   "RpcApiError: 'Cannot find usable pool pair.', code: -32600, method: testpoolswap"
```

**Review by Bushstar — APPROVED** [review]

**Review by hidiego — APPROVED** [review]

**Review by fuxingloh — APPROVED** [review]
LGTM

Tested on https://github.com/JellyfishSDK/jellyfish/pull/1814 with all test passing.

**Pull request merged**
