### PR TITLE
Add cancel previously running CI with new commits

### PR DESCRIPTION
**Pull request by sieniven**
## Summary

- This PR adds cancelling currently running CI workflows from the same PR, branch or tag with new commits.

## Implications

- Storage
  - [ ] Database reindex required
  - [ ] Database reindex optional
  - [ ] Database reindex not required
  - [x] None

- Consensus
  - [ ] Network upgrade required
  - [ ] Includes backward compatible changes
  - [ ] Includes consensus workarounds
  - [ ] Includes consensus refactors
  - [x] None

### CODE REVIEW

**Review by prasannavl — DISMISSED** [review]

**Comment by prasannavl** [comment]
Think `group: ${{ github.workflow }}-${{ github.ref }}` is quite equivalent to this current set from GH docs .
image

**Comment by prasannavl** [comment]
I think you want something like: 

```
group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
```

**Comment by sieniven** [comment]
> I think you want something like:
> 
> ```
> group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
> ```

This doesnt seem to work.

**Comment by sieniven** [comment]
Buggy PR after introducing these changes:
`group: ${{ github.workflow }}-${{ github.ref || github.run_id }}`

Recreating the PR.

**Pull request closed without merging**
