### PR TITLE
Feature masternode reward address

### PR DESCRIPTION
**Pull request by DeFiDev**
Forced reward address for masternodes

#### What kind of PR is this?:

/kind

#### Which issue(s) does this PR fixes?:

Fixes #

### CODE REVIEW

**Comment by ShengguangXiao** [comment]
Functionality test is good, but I think need to define a hard fork height for it.

**Review by monstrobishi — CHANGES_REQUESTED** [review]
Can you put hardfork height check for consensus breaking changes? Add hardfork called FUpgradeHeight

**Comment by ShengguangXiao** [comment]
@DeFiDev `ApplySetForcedRewardAddressTx` and `RemoveForcedRewardAddressMessage` also need to check hard fork height.

**Review by ShengguangXiao — APPROVED** [review]

**Comment by monstrobishi** [comment]
Closing PR until 1.8.x, will keep branch open

**Pull request closed without merging**
