### PR TITLE
Set CLIENT_VERSION to BUILD_DESC

### PR DESCRIPTION
**Pull request by bvbfan**
It sets CLIENT_VERSION accordingly to BUILD_DESC which is set at compilation time.

### CODE REVIEW

**Comment by monstrobishi** [comment]
will this reliably not crash depending on the string set?

**Comment by bvbfan** [comment]
Will not crash, if string not match pattern (means not equals or start with) `major, minor, rev` remains unchanged say 0-es.

**Review by monstrobishi — APPROVED** [review]

**Comment by monstrobishi** [comment]
Travis failed due to error:
```
The locale dependent function sscanf(...) appears to be used:
src/clientversion.cpp:        sscanf(BUILD_DESC, "v%d.%d.%d", &major, &minor, &rev);
Unnecessary locale dependence can cause bugs that are very
tricky to isolate and fix. Please avoid using locale dependent
functions if possible.
```

**Comment by bvbfan** [comment]
There is no locale here. `v.1.3.14`

**Comment by monstrobishi** [comment]
it's saying sscanf is locale dependent, maybe there is an alternative function?

**Comment by bvbfan** [comment]
We can use
```
 std::setlocale(LC_ALL, "C");
```
I've not aware of other function.

**Comment by bvbfan** [comment]
Use `std::stoi` a bit more ugly.

**Comment by bvbfan** [comment]
I'll exclude it in `lint-locale-dependence.sh` as others.

**Comment by uzyn** [comment]
@bvbfan This does not work. Running v1.3.15rc2

```
$ defi-cli -getinfo
{
  "version": 0, // it's now 0
  "protocolversion": 70016,
  "blocks": 519134,
}
```

**Comment by monstrobishi** [comment]
@uzyn this won't work with the rc versions because of the non numerical text in the build version

**Comment by uzyn** [comment]
@monstrobishi Got it. cool!

**Pull request merged**
