### PR TITLE
Add script to generate burn address

### PR DESCRIPTION
**Pull request by ShengguangXiao**
Add script to generate burn address

### CODE REVIEW

**Comment by monstrobishi** [comment]
This works great, will merge in.

One minor note, some addresses don't seem to generate valid address e.g.:

`8defichainburnaddressXXXXXXXYYFnKm` work but `8DeFiChainBurnAddressXXXXXXXXvVbAC` does not work, is this supposed to be the case?

**Review by monstrobishi — APPROVED** [review]

**Comment by uzyn** [comment]
Looks good, is there a possibility of making this work for capital letters too @ShengguangXiao ?

**Comment by ShengguangXiao** [comment]
@uzyn @uzyn 
The script can work for Capital characters too, but only start with some special characters are accepted by the DefiChain.
The Defi Mainnet address should start with string from 8F ~ 8d
The defi Testnet address start with string from 73 ~ 7R,
This is determined by the chain parameter 
```
base58Prefixes[PUBKEY_ADDRESS] = {0x12}; // '8' (0('1') for bitcoin)
```
and for testnet
```
base58Prefixes[PUBKEY_ADDRESS] = {0xf}; // '7' (111 ('m' or 'n') for bitcoin)
```

**Comment by monstrobishi** [comment]
Oh right thanks I missed that detail, could we make the script error out if it's not within either of those ranges?

**Comment by ShengguangXiao** [comment]
> Oh right thanks I missed that detail, could we make the script error out if it's not within either of those ranges? Don't need to add a new parameter, just check against both ranges

OK

**Comment by ShengguangXiao** [comment]
@monstrobishi @uzyn Updated

**Comment by monstrobishi** [comment]
This looks good merging

**Pull request merged**
