### PR TITLE
Improve overall node memory usage

### PR DESCRIPTION
**Pull request by bvbfan**
The high memory usage when `-acindex` is enabled is caused by `FlushStateToDisk` do actually flush when cache is going to end, (custom cache is not taken in calculation), periodic (DATABASE_FLUSH_INTERVAL is 24 hours) or when mode is ALWAYS (when node is going to shutting down). The patch aims to increase custom cache size as well as Flush occasionally when `CFlushableStorageKV` is going near maximum cache size, till now `changed` map going to be a couple of GiB, which can result in killing the daemon by the OS. New account rewards are introduced to reduce records in db and to increase performance when it's iterate. Limit in `listaccounthistory` is better exposed and proved by unit test. In result full resync should not take more than ~600 MB to operate, without performance loose.

### CODE REVIEW

**Comment by ShengguangXiao** [comment]
@bvbfan I tested this branch, the node can sync, but when i stop the node, it cannot shutdown properly(My instance is 8G ram, may be kipped by OS), so next time it will start to reindex again.

```
xo)
2021-01-02T16:15:35Z FindMostWorkChain: setBlockIndexCandidates: 2, filtered: 2
2021-01-02T16:15:35Z applied tx 44b0c7f145db9eb93565fb77872d021172c56690234717a2061bd22f86d30be7: Transfer AccountToAccount: from 76a9140f2536279049016bc20a577d542cd3d50d9fa49088ac to (a914a8687a29eeb0cb2f19a485c668730a72569056ed87->8.78587346@0)
2021-01-02T16:15:35Z UpdateTip: new best=61c782975b79d6e04d325533fb63779b7fe96cd40a1dc22949239ee9fc458f23 height=545038 version=0x20000000 log2_work=79.320812 tx=803102 date='2021-01-02T16:15:34Z' progress=1.000000 cache=148.5MiB(1102018txo)
2021-01-02T16:16:14Z FindMostWorkChain: setBlockIndexCandidates: 2, filtered: 2
2021-01-02T16:16:14Z UpdateTip: new best=fec24458e538fe9c82946af6765f0e5bee3b336b532278fe0760108b6305a15c height=545039 version=0x20000000 log2_work=79.320814 tx=803111 date='2021-01-02T16:16:14Z' progress=1.000000 cache=148.5MiB(1102020txo)
2021-01-02T16:16:30Z FindMostWorkChain: setBlockIndexCandidates: 2, filtered: 2
2021-01-02T16:16:30Z UpdateTip: new best=945d9a3802d83695d5ad3af633e67042a0772945b74874501086123c50c4208b height=545040 version=0x20000000 log2_work=79.320816 tx=803116 date='2021-01-02T16:16:30Z' progress=1.000000 cache=148.5MiB(1102023txo)
2021-01-02T16:16:57Z FindMostWorkChain: setBlockIndexCandidates: 2, filtered: 2
2021-01-02T16:16:57Z applied tx 021fc25ef0b793cc65e6c67c1309ee6903dc1e4da510d2d7e3d7a17e99fc42e9: Transfer AccountToAccount: from 76a9140626ee1adc4e052d3de53cce8c8887294bee11eb88ac to (a914d5108609ff80cbc6139120668320a2f4cc8e25bd87->0.00020000@2)
2021-01-02T16:16:57Z UpdateTip: new best=7e2f5fd148aea4794f0adfd3b851eacc7467540a03f7a830d5636dc9584dc270 height=545041 version=0x20000000 log2_work=79.320819 tx=803126 date='2021-01-02T16:16:57Z' progress=1.000000 cache=148.5MiB(1102026txo)
2021-01-02T16:17:09Z tor: Thread interrupt
2021-01-02T16:17:09Z Shutdown: In progress...
2021-01-02T16:17:09Z opencon thread exit
2021-01-02T16:17:09Z torcontrol thread exit
2021-01-02T16:17:09Z addcon thread exit
2021-01-02T16:17:09Z net thread exit
2021-01-02T16:17:09Z msghand thread exit
2021-01-02T16:17:09Z scheduler thread interrupt
2021-01-02T16:17:09Z Dumped mempool: 1.1e-05s to copy, 0.002212s to dump
Killed
```

**Comment by bvbfan** [comment]
Probably you made a mistake, that's master `cache=148.5MiB` actually now you can see such a values, it's flush pretty earlier.
https://github.com/DeFiCh/ain/pull/156/commits/e87f281a42f823aa5bca0c859a69e439ac98ee2f#diff-97c3a52bc5fad452d82670a7fd291800bae20c7bc35bb82686c2c0a4ea7b5b98R2435

**Comment by ShengguangXiao** [comment]
I added some logs to track the cache size, i think what you fix is the custom view memory size, but the `cache=148.5MiB` is the `CoinsTip().DynamicMemoryUsage()`
```
2021-01-03T13:55:58Z mode 0, cacheSize: 156,280,992, customViewSize: 24,018,736
```

**Comment by bvbfan** [comment]
> I added some logs to track the cache size, i think what you fix is the custom view memory size

Because that's the problem, map inside `CFlushableStorageKV` became GiB, that's because no flush is called.

**Review by monstrobishi — APPROVED** [review]

**Pull request merged**
