### PR TITLE
Add version suffix to `getversioninfo`

### PR DESCRIPTION
**Pull request by dcorral**
#### What kind of PR is this?:

/kind fix

#### What this PR does / why we need it:

Adds versionSuffix to `getversioninfo` and tests
Fixes build errors on #1339

### CODE REVIEW

**Comment by dcorral** [comment]
Release build action on fork green -> https://github.com/dcorral/ain/actions/runs/3697665161

**Comment by shohamc1** [comment]
Ignore Jellyfish failure - flaky test.

**Comment by prasannavl** [comment]
Reprioritizing to first look at BTC updates and how to integrate this as close to BTC vanilla codebase.

**Comment by prasannavl** [comment]
Closing stale PRs

**Pull request closed without merging**
