### PR TITLE
Minimize custom tx logs

### PR DESCRIPTION
**Pull request by bvbfan**
It can speedup sync since writing to stdout as well in file is slow.

### CODE REVIEW

**Comment by monstrobishi** [comment]
Can you also reduce frequency or remove logging of duplicate anchor payment, this one is flooding testnet logs

**Comment by bvbfan** [comment]
@ShengguangXiao  remove duplicate anchor reward log, actually it will be good to be shown only once but  don't think it worth.

**Comment by ShengguangXiao** [comment]
> @ShengguangXiao i remove duplicate anchor reward log, actually it will be good to be shown only once but don't think it worth.

I think can be removed, I added the log to verify the logic is working, now the verification is done, so safe to remove.

**Review by ShengguangXiao — APPROVED** [review]

**Comment by monstrobishi** [comment]
travis failed saying argument conversion failed for reward address

**Pull request merged**
